# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee37d7d044fcf7e9a007e07236b21129a140e71b60ef584e78f40c390e4a99eb1fc99f1f96f52f10b68fb47bc314f5d6343961040e915a294ac6a54edf6ea442

test:
  secret_key_base: 84848d0c8e5f1dc6002ac916a0b8788aaffb24f7a72fb011ab20e19bfaddfe9b4973e6d362a2893227ca748cea9bd6348371b21358b5e17cde820c8e9f27aa6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
